### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nsunami** [hexa-/SAM-vectors#1]
I really liked your vector drawings. Thank you for your work. Would you mind providing a licensing term for this repo? Currently, no license is given and thus all rights are reserved by the owner. ([more info on this here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)) I thought it would be really helpful for everyone who wants to use your work (including myself) to have a license explicitly stated.

**Comment by hexa-** [comment]
Hi,

Thanks for pointing this out. Added  CC0-1.0 License for the SAM vectors.
